#!/usr/bin/env python3
"""Generate per-module -D symbol rename argsfiles for the ET:L wasm build.

The engine normally loads cgame/ui/qagame as native shared libraries, where
each module keeps private copies of common symbols (trap_* glue, Com_Printf,
bg_* data, shared cvars, ui_shared...). Statically linking them into one wasm
binary collides. This script diffs the defined symbols of the engine objects
and the three mod archives and emits, per module, `-D<sym>=<prefix><sym>`
compile definitions so every module keeps its own isolated copies - exactly
like the native DLL layout.

Usage:
  python gen_mod_renames.py <build_dir> <llvm_bin_dir>

Run before (re)configuring CMake; it writes:
  <build_dir>/cgame_renames.txt / ui_renames.txt / qagame_renames.txt
"""
import glob
import os
import subprocess
import sys


def defined_symbols(nm, path):
    out = subprocess.run([nm, "--defined-only", path], capture_output=True, text=True).stdout
    syms = set()
    for line in out.splitlines():
        parts = line.split()
        # keep only EXTERNAL definitions (uppercase types); file-local statics
        # (lowercase types, llvm-internal dotted names) never collide
        if len(parts) >= 3 and parts[-2] in ("T", "D", "B", "R", "W"):
            syms.add(parts[-1])
    return syms


def main():
    build = os.path.abspath(sys.argv[1])
    llvm_bin = sys.argv[2] if len(sys.argv) > 2 else ""
    nm = os.path.join(llvm_bin, "llvm-nm.exe" if os.name == "nt" else "llvm-nm") if llvm_bin else "llvm-nm"

    engine_dir = os.path.join(build, "CMakeFiles", "etl.dir")
    engine_syms = set()
    for obj in glob.glob(os.path.join(engine_dir, "**", "*.o"), recursive=True):
        engine_syms |= defined_symbols(nm, obj)

    groups = {}
    for mod, lib in (("cgame", "libcgame.a"), ("ui", "libui.a"), ("qagame", "libqagame.a")):
        lib_path = os.path.join(build, lib)
        if os.path.exists(lib_path):
            groups[mod] = defined_symbols(nm, lib_path)
        else:
            groups[mod] = set()
            print(f"warning: {lib_path} not found (build the mod targets once first)")

    prefixes = {"cgame": "cg_", "ui": "ui_", "qagame": "qa_"}

    # symbols defined by more than one group (engine counts as one group)
    all_syms = {}
    all_syms["engine"] = engine_syms
    all_syms.update(groups)

    from collections import Counter
    owner_count = Counter()
    for syms in all_syms.values():
        owner_count.update(syms)
    duplicates = {s for s, n in owner_count.items() if n > 1}

    # never rename these
    duplicates -= {"main"}

    total = 0
    import re
    ident = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
    for mod, prefix in prefixes.items():
        renames = sorted(s for s in groups[mod] & duplicates if ident.match(s))
        out_path = os.path.join(build, f"{mod}_renames.h")
        with open(out_path, "w") as f:
            f.write("/* generated by misc/web/gen_mod_renames.py - do not edit */\n")
            f.write("#pragma once\n")
            for s in renames:
                f.write(f"#define {s} {prefix}{s}\n")
        total += len(renames)
        print(f"{mod}: {len(renames)} renames -> {out_path}")
    print(f"total: {total} renames across {len(duplicates)} duplicated symbols")


if __name__ == "__main__":
    main()
