# Produce a worker whose bytes change with every coherent engine bundle.
find_program(PWA_NODE NAMES node nodejs REQUIRED)
execute_process(COMMAND "${PWA_NODE}" "${SOURCE}/test_built_launcher.cjs" "${BUILD}" RESULT_VARIABLE PWA_PARSE_RESULT)
if(NOT PWA_PARSE_RESULT EQUAL 0)
  message(FATAL_ERROR "Generated browser JavaScript failed syntax validation")
endif()
set(PWA_CORE etl.html etl.js etl.wasm etl.data manifest.webmanifest icon-192.png icon-512.png)
foreach(NAME manifest.webmanifest icon-192.png icon-512.png)
  configure_file("${SOURCE}/pwa/${NAME}" "${BUILD}/${NAME}" COPYONLY)
endforeach()
set(PWA_ENTRIES "")
set(PWA_HASHES "")
foreach(NAME IN LISTS PWA_CORE)
  file(SHA256 "${BUILD}/${NAME}" HASH)
  string(APPEND PWA_ENTRIES "{url:'${NAME}',sha256:'${HASH}'},\n")
  string(APPEND PWA_HASHES "${HASH}")
endforeach()
file(SHA256 "${SOURCE}/sw.js.in" WORKER_HASH)
file(READ "${SOURCE}/pwa/recovery.html" PWA_RECOVERY_HTML)
file(SHA256 "${SOURCE}/pwa/recovery.html" RECOVERY_HASH)
string(REPLACE "\\" "\\\\" PWA_RECOVERY_HTML "${PWA_RECOVERY_HTML}")
string(REPLACE "\"" "\\\"" PWA_RECOVERY_HTML "${PWA_RECOVERY_HTML}")
string(REPLACE "\r" "" PWA_RECOVERY_HTML "${PWA_RECOVERY_HTML}")
string(REPLACE "\n" "\\n" PWA_RECOVERY_HTML "${PWA_RECOVERY_HTML}")
set(PWA_RECOVERY_JSON "\"${PWA_RECOVERY_HTML}\"")
string(SHA256 PWA_VERSION "${PWA_HASHES}${WORKER_HASH}${RECOVERY_HASH}")
configure_file("${SOURCE}/sw.js.in" "${BUILD}/sw.js" @ONLY)
execute_process(COMMAND "${PWA_NODE}" "${SOURCE}/test_built_launcher.cjs" "${BUILD}" RESULT_VARIABLE PWA_PARSE_RESULT)
if(NOT PWA_PARSE_RESULT EQUAL 0)
  message(FATAL_ERROR "Generated offline worker failed syntax validation")
endif()
